### ISSUE TITLE
conda-izing SNVPhyl

### ISSUE THREAD

**Issue by pvanheus** [phac-nml/snvphyl-galaxy#1]
Hi there. I'm interesting in making conda wrappers for the SNVPhyl pipeline tools. To that end:

1. I want to write recipes for the SNVPhyl [tool dependencies](https://github.com/phac-nml/snvphyl-galaxy/blob/development/tools/package_snvphyl/tool_dependencies.xml). Some of the dependencies exist in bioconda, others do not. In general 'generic' packages belong in conda-forge and I've made a start on wrappers in this PR: https://github.com/conda-forge/staged-recipes/pull/3261

2. Next I want to tackle the tools listed in the [snvphyl-tools](https://github.com/phac-nml/snvphyl-galaxy/tree/development/tools/snvphyl-tools) directory and create conda recipes for them. These largely draw from the script in the [snvphyl-tools](https://github.com/phac-nml/snvphyl-tools) repository. The install procedure used in the existing Galaxy package is rather unique though.

3. The bcftools based tools, bcftools_call and bcftools_view, also phyml, seqtk and smalt, rely on dependencies that are already in bioconda. Only the wrappers need updating to link these to those dependencies, if the versions of the dependencies from bioconda are appropriate.

4. Finally the wombac tool requires more Perl [dependencies](https://github.com/phac-nml/snvphyl-galaxy/blob/development/tools/package_wombac/tool_dependencies.xml) and the tool itself to be added a conda recipes.

**Comment by apetkau** [comment]
That would be awesome :). It's something I had wanted to do at some point but haven't had the time. Some of the code is probably not as organized that it could be so I would welcome any feedback or suggestions on this.

1. Cool, thank you. That all sounds good to me.

2. Yes, installing tools from [snvphyl-tools](https://github.com/phac-nml/snvphyl-tools) repo is a bit more complicated than it could be. Most of the scripts in there rely mainly on Perl modules which isn't so bad. Some have other dependencies (e.g., [find-repeats.pl](https://github.com/phac-nml/snvphyl-tools/blob/master/find-repeats.pl) relies on MUMmer). The more complicated tool would be [consolidate_vcfs.pl](https://github.com/phac-nml/snvphyl-tools/blob/master/consolidate_vcfs.pl) which relies on bcftools, and a custom bcftools plugin [filter_snv_density](https://github.com/phac-nml/snvphyl-tools/blob/master/bcfplugins/bcftools-1.3/plugins/filter_snv_density.c). The way we were getting this to compile was to include a copy of the bcftools 1.3 source in our repository and compiling it ourselves, but there's got to be an easier way to do this.

3. It's likely that the versions of those dependencies are appropriate. I would welcome any updates to the wrappers you can provide.

4. The wombac tool is currently unused in SNVPhyl and I should probably remove it from this repo (so don't worry about writing wrappers for it).  Part of the tool was used at one point as a quick way of simulating reads in order to run SNVPhyl on assembled genomes with no reads, but there are other read simulators already in Galaxy and it was never part of the automated pipeline.

I also want to include @Takadonet and @csieffert on this discussion as they have worked on some of these tools and could provide input if something doesn't make sense.

Thanks for taking the time to do this, I really appreciate it.

**Comment by pvanheus** [comment]
I'm in Freetown, Sierra Leone for the week but have been working on this in the evenings. Just including @thobalose and @zipho in this thread - I'll put up more details related to progress in the next days.

**Comment by Takadonet** [comment]
Merged. Near future will push new suite snvphyl onto main tool shed.
